version: "3.8"

volumes:
  mongodb_data:

services:
  mongodb:
    container_name: mongodb_development
    image: mongo:8.0.15
    hostname: mongodb_development
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ARGS: "--quiet"
    ports:
      - "18001:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: >
        mongosh --quiet -u root -p "$$MONGO_INITDB_ROOT_PASSWORD" --eval "db.adminCommand('ping').ok" || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
    mem_limit: 1g
    memswap_limit: 1.5g